name: Docker Image Push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
    
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_I4TECHLAB_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_I4TECHLAB_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
        
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag i4techlab/docencia-schneider-nodered:latest
      
    - name: Docker Push
      run: docker push i4techlab/docencia-schneider-nodered
